name: Delete Old Workflows
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,15 * *'
    # Run on the 1st and 15th day of the month, at 00:00.

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 14
          keep_minimum_runs: 2
